# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evergreen
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Never stop growing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ianrahman.com" # the base hostname & protocol for your site
twitter_username: ian_rahman_
github_username:  ianrahman

# Build settings
markdown: kramdown

theme: jekyll-theme-tactile